services:
  redis:
    image: redis:8.0.2-alpine@sha256:48501c5ad00d5563bc30c075c7bcef41d7d98de3e9a1e6c752068c66f0a8463b
    networks:
      - main_net
    volumes:
      - ./redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    logging:
      driver: loki
      options:
        mode: non-blocking
        loki-url: ${LOKI_URL}
        loki-batch-size: "10"
        loki-timeout: "10s"
        loki-retries: "3"

  scylladb:
    image: scylladb/scylla:2025.1.2@sha256:84e914792c61a7703ff616bf6ee6d4becbcf68845221bd2458fcab10ef64302c
    networks:
      - main_net
    volumes:
      - ./scylladb_data:/var/lib/scylla
    command: --smp=1 --memory=1G --overprovisioned=1 --api-address=0.0.0.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    logging:
      driver: loki
      options:
        mode: non-blocking
        loki-url: ${LOKI_URL}
        loki-batch-size: "10"
        loki-timeout: "10s"
        loki-retries: "3"

  rust:
    image: boiler_rust:latest
    networks:
      - main_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    secrets:
      - RUST_FROM_EMAIL
      - RUST_FROM_EMAIL_PASSWORD
      - RUST_FROM_EMAIL_SERVER
      - API_TOKEN
    logging:
      driver: loki
      options:
        mode: non-blocking
        loki-url: ${LOKI_URL}
        loki-batch-size: "10"
        loki-timeout: "10s"
        loki-retries: "3"
    environment:
      - RUST_PORT=${RUST_PORT}
      - RUST_LOG=${RUST_LOG}
      - RUST_DB_URI=${RUST_DB_URI}
      - RUST_REDIS_URL=${RUST_REDIS_URL}
      - RUST_MAX_SESSIONS=${RUST_MAX_SESSIONS}
      - SVELTE_URL=${SVELTE_URL}

  svelte:
    image: boiler_svelte:latest
    networks:
      - main_net
    secrets:
      - API_TOKEN
    command: sh -c "export API_TOKEN=$$(cat /run/secrets/API_TOKEN) && node build"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${SVELTE_PORT}

  caddy:
    image: boiler_caddy:latest
    networks:
      - main_net
    ports:
      - "80:80"
      - "443:443"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    logging:
      driver: loki
      options:
        mode: non-blocking
        loki-url: ${LOKI_URL}
        loki-batch-size: "10"
        loki-timeout: "10s"
        loki-retries: "3"
    command: sh -c "caddy run --config /etc/caddy/Caddyfile"
    environment:
      - CADDY_LOG_ROTATE_DAYS=356
      - CADDY_LOG_ROTATE_SIZE=10000
      - CADDY_DOMAIN=${CADDY_DOMAIN}
      - RUST_NAME=${RUST_NAME}
      - RUST_PORT=${RUST_PORT}
      - SVELTE_NAME=${SVELTE_NAME}
      - SVELTE_PORT=${SVELTE_PORT}
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/logs:/var/log/caddy
      - ./caddy/config/Caddyfile.local:/etc/caddy/Caddyfile

secrets:
  RUST_FROM_EMAIL:
    external: true
  RUST_FROM_EMAIL_PASSWORD:
    external: true
  RUST_FROM_EMAIL_SERVER:
    external: true
  API_TOKEN:
    external: true

networks:
  main_net:
    external: true
    name: main_net
  monitor_net:
    external: true
    name: monitor_net
