services:
  boiler_rust:
    build:
      context: ../backend
    image: boiler_rust:latest

  boiler_svelte:
    build:
      args:
        - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL}
        - PRIVATE_BACKEND_URL=${PRIVATE_BACKEND_URL}
        - PUBLIC_TEMP_SESSION_DURATION_SECS=${PUBLIC_TEMP_SESSION_DURATION_SECS}
      context: ../frontend
    image: boiler_svelte:latest

  boiler_caddy:
    build:
      context: ./caddy
    image: boiler_caddy:latest
