global:
  scrape_interval: 15s
  evaluation_interval: 1m
  scrape_timeout: 10s

scrape_configs:
  - job_name: "boiler-metrics"
    scheme: http
    metrics_path: "/metrics"
    static_configs:
      - targets: ["rust:3000"]
    relabel_configs:
      - source_labels: [__param_target]
        target_label: instance
  - job_name: "db-metrics"
    scheme: http
    metrics_path: "/metrics"
    static_configs:
      - targets: ["scylladb:9180"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
